class YasinVerse {
  final int number;
  final String arabic;
  final String transliteration;
  final String translation;

  const YasinVerse({
    required this.number,
    required this.arabic,
    required this.transliteration,
    required this.translation,
  });
}

class YasinData {
  static const List<YasinVerse> verses = [
    YasinVerse(
      number: 1,
      arabic: 'بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ\n\nيس',
      transliteration: 'Bismillaahir Rahmaanir Raheem\n\nYaa-Seeen',
      translation: 'Dengan nama Allah Yang Maha Pengasih, Maha Penyayang.\n\n1) Ya Sin',
    ),
    YasinVerse(
      number: 2,
      arabic: 'وَالْقُرْآنِ الْحَكِيمِ',
      transliteration: 'Wal-Qur-aanil-Hakeem',
      translation: '2) Demi Al-Qur\'an yang penuh hikmah,',
    ),
    YasinVerse(
      number: 3,
      arabic: 'إِنَّكَ لَمِنَ الْمُرْسَلِينَ',
      transliteration: 'Innaka laminal mursaleen',
      translation: '3) sungguh, engkau (Muhammad) adalah salah seorang dari rasul-rasul,',
    ),
    YasinVerse(
      number: 4,
      arabic: 'عَلَىٰ صِرَاطٍ مُّسْتَقِيمٍ',
      transliteration: '\'Alaa Siraatim Mustaqeem',
      translation: '4) (yang berada) di atas jalan yang lurus,',
    ),
    YasinVerse(
      number: 5,
      arabic: 'تَنزِيلَ الْعَزِيزِ الرَّحِيمِ',
      transliteration: 'Tanzeelal \'Azeezir Raheem',
      translation: '5) (as-sebagai wahyu) yang diturunkan oleh (Allah) Yang Mahaperkasa, Maha Penyayang,',
    ),
    YasinVerse(
      number: 6,
      arabic: 'لِتُنذِرَ قَوْمًا مَّا أُنذِرَ آبَاؤُهُمْ فَهُمْ غَافِلُونَ',
      transliteration: 'Litunzira qawmam maaa unzira aabaaa\'uhum fahum ghaafiloon',
      translation: '6) agar engkau memberi peringatan kepada suatu kaum yang nenek moyangnya belum pernah diberi peringatan, karena itu mereka lalai.',
    ),
    YasinVerse(
      number: 7,
      arabic: 'لَقَدْ حَقَّ الْقَوْلُ عَلَىٰ أَكْثَرِهِمْ فَهُمْ لَا يُؤْمِنُونَ',
      transliteration: 'Laqad haqqal qawlu \'alaaa aksarihim fahum laa yu\'minoon',
      translation: '7) Sungguh, pasti berlaku perkataan (hukuman) terhadap kebanyakan mereka, karena mereka tidak beriman.',
    ),
    YasinVerse(
      number: 8,
      arabic: 'إِنَّا جَعَلْنَا فِي أَعْنَاقِهِمْ أَغْلَالًا فَهِيَ إِلَى الْأَذْقَانِ فَهُم مُّقْمَحُونَ',
      transliteration: 'Innaa ja\'alnaa feee a\'naaqihim aghlaalan fahiya ilal azqaani fahum muqmahoon',
      translation: '8) Sungguh, Kami telah memasang belenggu di leher mereka, lalu tangan mereka (diangkat) ke dagu, karena itu mereka tertengadah.',
    ),
    YasinVerse(
      number: 9,
      arabic: 'وَجَعَلْنَا مِن بَيْنِ أَيْدِيهِمْ سَدًّا وَمِنْ خَلْفِهِمْ سَدًّا فَأَغْشَيْنَاهُمْ فَهُمْ لَا يُبْصِرُونَ',
      transliteration: 'Wa ja\'alnaa mim baini aydeehim saddanw-wa min khalfihim saddan fa aghshai naahum fahum laa yubsiroon',
      translation: '9) Dan Kami jadikan di hadapan mereka sekat (dinding) dan di belakang mereka juga sekat, dan Kami tutup (mata) mereka sehingga mereka tidak dapat melihat.',
    ),
    YasinVerse(
      number: 10,
      arabic: 'وَسَوَاءٌ عَلَيْهِمْ أَأَنذَرْتَهُمْ أَمْ لَمْ تُنذِرْهُمْ لَا يُؤْمِنُونَ',
      transliteration: 'Wa sawaaa\'un \'alaihim \'a-anzartahum am lam tunzirhum laa yu\'minoon',
      translation: '10) Dan sama saja bagi mereka, apakah engkau memberi peringatan kepada mereka atau engkau tidak memberi peringatan kepada mereka, mereka tidak akan beriman juga.',
    ),
    YasinVerse(
      number: 11,
      arabic: 'إِنَّمَا تُنذِرُ مَنِ اتَّبَعَ الذِّكْرَ وَخَشِيَ الرَّحْمَٰنَ بِالْغَيْبِ ۖ فَبَشِّرْهُ بِمَغْفِرَةٍ وَأَجْرٍ كَرِيمٍ',
      transliteration: 'Innamaa tunziru manit taba \'az-Zikra wa khashiyar Rahmaana bilghaib, fabashshirhu bimaghfiratinw-wa ajrin kareem',
      translation: '11) Sesungguhnya engkau hanya memberi peringatan kepada orang-orang yang mau mengikuti peringatan dan yang takut kepada Tuhan Yang Maha Pengasih, walaupun mereka tidak melihat-Nya. Maka berilah mereka kabar gembira dengan ampunan dan pahala yang mulia.',
    ),
    YasinVerse(
      number: 12,
      arabic: 'إِنَّا نَحْنُ نُحْيِي الْمَوْتَىٰ وَنَكْتُبُ مَا قَدَّمُوا وَآثَارَهُمْ ۚ وَكُلَّ شَيْءٍ أَحْصَيْنَاهُ فِي إِمَامٍ مُّبِينٍ',
      transliteration: 'Innaa Nahnu nuhyil mawtaa wa naktubu maa qaddamoo wa aasaarahum; wa kulla shai\'in ahsainaahu feee Imaamim Mubeen',
      translation: '12) Sungguh, Kamilah yang menghidupkan orang-orang yang mati, dan Kamilah yang mencatat apa yang telah mereka kerjakan dan bekas-bekas yang mereka (tinggalkan). Dan segala sesuatu Kami kumpulkan dalam Kitab yang jelas (Lauh Mahfuzh).',
    ),
    YasinVerse(
      number: 13,
      arabic: 'وَاضْرِبْ لَهُم مَّثَلًا أَصْحَابَ الْقَرْيَةِ إِذْ جَاءَهَا الْمُرْسَلُونَ',
      transliteration: 'Wadrib lahum masalan Ashaabal Qaryatih; iz jaaa\'ahal mursaloon',
      translation: '13) Dan buatlah suatu perumpamaan bagi mereka, yaitu penduduk suatu negeri, ketika utusan-utusan datang kepada mereka;',
    ),
    YasinVerse(
      number: 14,
      arabic: 'إِذْ أَرْسَلْنَا إِلَيْهِمُ اثْنَيْنِ فَكَذَّبُوهُمَا فَعَزَّزْنَا بِثَالِثٍ فَقَالُوا إِنَّا إِلَيْكُم مُّرْسَلُونَ',
      transliteration: 'Iz arsalnaaa ilaihimusnaini fakazzaboohumaa fa\'azzaznaa bisaalisin faqaalooo innaaa ilaikum mursaloon',
      translation: '14) (yaitu) ketika Kami mengutus kepada mereka dua orang utusan, lalu mereka mendustakan keduanya; kemudian Kami kuatkan dengan (utusan) yang ketiga, maka ketiga (utusan itu) berkata, “Sungguh, kami adalah orang-orang yang diutus kepadamu.”',
    ),
    YasinVerse(
      number: 15,
      arabic: 'قَالُوا مَا أَنتُمْ إِلَّا بَشَرٌ مِّثْلُنَا وَمَا أَنزَلَ الرَّحْمَٰنُ مِن شَيْءٍ إِنْ أَنتُمْ إِلَّا تَكْذِبُونَ',
      transliteration: 'Qaaloo maaa antum illaa basharum mislunaa wa maaa anzalar Rahmaanu min shai\'in in antum illaa takziboon',
      translation: '15) Mereka (penduduk negeri) menjawab, “Kamu ini hanyalah manusia seperti kami, dan (Allah) Yang Maha Pengasih tidak menurunkan sesuatu apa pun; kamu hanyalah pendusta belaka.”',
    ),
    YasinVerse(
      number: 16,
      arabic: 'قَالُوا رَبُّنَا يَعْلَمُ إِنَّا إِلَيْكُمْ لَمُرْسَلُونَ',
      transliteration: 'Qaaloo Rabbunaa ya\'lamu innaaa ilaikum lamursaloon',
      translation: '16) Mereka berkata, “Tuhan kami mengetahui sesungguhnya kami adalah utusan-utusan(-Nya) kepada kamu.',
    ),
    YasinVerse(
      number: 17,
      arabic: 'وَمَا عَلَيْنَا إِلَّا الْبَلَاغُ الْمُبِينُ',
      transliteration: 'Wa maa \'alainaaa illal balaaghul mubeen',
      translation: '17) Dan kewajiban kami hanyalah menyampaikan (perintah Allah) dengan jelas.”',
    ),
    YasinVerse(
      number: 18,
      arabic: 'قَالُوا إِنَّا تَطَيَّرْنَا بِكُمْ ۖ لَئِن لَّمْ تَنتَهُوا لَنَرْجُمَنَّكُمْ وَلَيَمَسَّنَّكُم مِّنَّا عَذَابٌ أَلِيمٌ',
      transliteration: 'Qaaloo innaa tataiyarnaa bikum la\'il-lam tantahoo lanar jumannakum wa la-yamassan nakum minnaa \'azaabun aleem',
      translation: '18) Mereka menjawab, “Sesungguhnya kami bernasib malang karena kamu. Sungguh, jika kamu tidak berhenti (menyeru kami), niscaya kami rajam kamu dan kamu pasti akan merasakan siksaan yang pedih dari kami.”',
    ),
    YasinVerse(
      number: 19,
      arabic: 'قَالُوا طَائِرُكُم مَّعَكُمْ ۚ أَئِن ذُكِّرْتُم ۚ بَلْ أَنتُمْ قَوْمٌ مُّسْرِفُونَ',
      transliteration: 'Qaaloo taaa\'irukum ma\'akum; a\'in zukkirtum; bal antum qawmum musrifoon',
      translation: '19) Mereka (utusan-utusan) itu berkata, “Kemalangan kamu itu adalah karena kamu sendiri. Apakah karena kamu diberi peringatan? Sebenarnya kamu adalah kaum yang melampaui batas.”',
    ),
    YasinVerse(
      number: 20,
      arabic: 'وَجاءَ مِنْ أَقْصَى الْمَدِينَةِ رَجُلٌ يَسْعَىٰ قَالَ يَا قَوْمِ اتَّبِعُوا الْمُرْسَلِينَ',
      transliteration: 'Wa jaaa\'a min aqsal madeenati rajuluny yas\'aa qaala yaa qawmit tabi\'ul mursaleen',
      translation: '20) Dan datanglah dari ujung kota, seorang laki-laki dengan bergegas dia berkata, “Wahai kaumku! Ikutilah utusan-utusan itu.',
    ),
    YasinVerse(
      number: 21,
      arabic: 'اتَّبِعُوا مَن لَّا يَسْأَلُكُمْ أَجْرًا وَهُم مُّهْتَدُونَ',
      transliteration: 'Ittabi\'oo mal-laa yas\'alukum ajranw-wa hum muhtadoon',
      translation: '21) Ikutilah orang yang tidak meminta imbalan kepadamu; dan mereka adalah orang-orang yang mendapat petunjuk.',
    ),
    YasinVerse(
      number: 22,
      arabic: 'وَمَا لِيَ لَا أَعْبُدُ الَّذِي فَطَرَنِي وَإِلَيْهِ تُرْجَعُونَ',
      transliteration: 'Wa maa liya laaa a\'budul lazee fataranee wa ilaihi turja\'oon',
      translation: '22) Dan tidak ada alasan bagiku untuk tidak menyembah (Allah) yang telah menciptakanku dan hanya kepada-Nyalah kamu akan dikembalikan.',
    ),
    YasinVerse(
      number: 23,
      arabic: 'أَأَتَّخِذُ مِن دُونِهِ آلِهَةً إِن يُرِدْنِ الرَّحْمَٰنُ بِضُرٍّ لَّا تُغْنِ عَنِّي شَفَاعَتُهُمْ شَيْئًا وَلَا يُنقِذُونِ',
      transliteration: '\'A-attakhizu min dooniheee aalihatan iny-yuridnir Rahmaanu bidurril-laa tughni \'annee shafaa \'atuhum shai \'anw-wa laa yunqizoon',
      translation: '23) Mengapa aku akan menyembah tuhan-tuhan selain-Nya? Jika (Allah) Yang Maha Pengasih menghendaki bencana terhadapku, pasti pertolongan mereka tidak berguna sama sekali bagi diriku dan mereka (juga) tidak dapat menyelamatkanku.',
    ),
    YasinVerse(
      number: 24,
      arabic: 'إِنِّي إِذًا لَّفِي ضَلَالٍ مُّبِينٍ',
      transliteration: 'Inneee izal-lafee dalaa-lim-mubeen',
      translation: '24) Sesungguhnya jika aku (berbuat) begitu, pasti aku berada dalam kesesatan yang nyata.',
    ),
    YasinVerse(
      number: 25,
      arabic: 'إِنِّي آمَنتُ بِرَبِّكُمْ فَاسْمَعُونِ',
      transliteration: 'Inneee aamantu bi Rabbikum fasma\'oon',
      translation: '25) Sesungguhnya aku telah beriman kepada Tuhanmu; maka dengarkanlah (pengakuan keimanan)-ku.”',
    ),
    YasinVerse(
      number: 26,
      arabic: 'قِيلَ ادْخُلِ الْجَنَّةَ ۖ قَالَ يَا لَيْتَ قَوْمِي يَعْلَمُونَ',
      transliteration: 'Qeelad khulil Jannnah; qaala yaa laita qawmee ya\'lamoon',
      translation: '26) Dikatakan (kepadanya), “Masuklah ke surga.” Dia (laki-laki itu) berkata, “Alangkah baiknya sekiranya kaumku mengetahui,',
    ),
    YasinVerse(
      number: 27,
      arabic: 'بِمَا غَفَرَ لِي رَبِّي وَجَعَلَنِي مِنَ الْمُكْرَمِينَ',
      transliteration: 'Bimaa ghafara lee Rabbee wa ja\'alanee minal mukrameen',
      translation: '27) apa yang menyebabkan Tuhanku memberi ampun kepadaku dan menjadikan aku termasuk orang-orang yang telah dimuliakan.”',
    ),
    YasinVerse(
      number: 28,
      arabic: '۞ وَمَا أَنزَلْنَا عَلَىٰ قَوْمِهِ مِن بَعْدِهِ مِن جُندٍ مِّنَ السَّمَاءِ وَمَا كُنَّا مُنزِلِينَ',
      transliteration: 'Wa maaa anzalnaa \'alaa qawmihee mim ba\'dihee min jundim minas-samaaa\'i wa maa kunnaa munzileen',
      translation: '28) Dan setelah dia (meninggal), Kami tidak menurunkan suatu pasukan pun dari langit kepada kaumnya, dan Kami tidak perlu menurunkannya.',
    ),
    YasinVerse(
      number: 29,
      arabic: 'إِن كَانَتْ إِلَّا صَيْحَةً وَاحِدَةً فَإِذَا هُمْ خَامِدُونَ',
      transliteration: 'In kaanat illaa saihatanw waahidatan fa-izaa hum khaamidoon',
      translation: '29) Tidak ada siksaan terhadap mereka melainkan dengan satu teriakan saja; maka seketika itu mereka mati.',
    ),
    YasinVerse(
      number: 30,
      arabic: 'يَا حَسْرَةً عَلَى الْعِبَادِ ۚ مَا يَأْتِيهِم مِّن رَّسُولٍ إِلَّا كَانُوا بِهِ يَسْتَهْزِئُونَ',
      transliteration: 'Yaa hasratan \'alal \'ibaad; maa yaateehim mir Rasoolin illaa kaanoo bihee yastahzi \'oon',
      translation: '30) Alangkah besar penyesalan terhadap hamba-hamba itu, setiap datang seorang rasul kepada mereka, mereka selalu memperolok-olokkannya.',
    ),
    YasinVerse(
      number: 31,
      arabic: 'أَلَمْ يَرَوْا كَمْ أَهْلَكْنَا قَبْلَهُم مِّنَ الْقُرُونِ أَنَّهُمْ إِلَيْهِمْ لَا يَرْجِعُونَ',
      transliteration: 'Alam yaraw kam ahlak naa qablahum minal qurooni annahum ilaihim laa yarji\'oon',
      translation: '31) Tidakkah mereka mengetahui berapa banyak umat-umat sebelum mereka yang telah Kami binasakan. Orang-orang (yang telah Kami binasakan) itu tidak ada yang kembali kepada mereka.',
    ),
    YasinVerse(
      number: 32,
      arabic: 'وَإِن كُلٌّ لَّمَّا جَمِيعٌ لَّدَيْنَا مُحْضَرُونَ',
      transliteration: 'Wa in kullul lammaa jamee\'ul-ladainaa muhdaroon',
      translation: '32) Dan setiap (umat), semuanya akan dihadapkan kepada Kami.',
    ),
    YasinVerse(
      number: 33,
      arabic: 'وَآيَةٌ لَّهُمُ الْأَرْضُ الْمَيْتَةُ أَحْيَيْنَاهَا وَأَخْرَجْنَا مِنْهَا حَبًّا فَمِنْهُ يَأْكُلُونَ',
      transliteration: 'Wa Aayatul lahumul ardul maitatu ahyainaahaa wa akhrajnaa minhaa habban faminhu yaakuloon',
      translation: '33) Dan suatu tanda (kebesaran Allah) bagi mereka adalah bumi yang mati (tandus). Kami hidupkan bumi itu dan Kami keluarkan darinya biji-bijian, maka dari (biji-bijian) itu mereka makan.',
    ),
    YasinVerse(
      number: 34,
      arabic: 'وَجَعَلْنَا فِيهَا جَنَّاتٍ مِّن نَّخِيلٍ وَأَعْنَابٍ وَفَجَّرْنَا فِيهَا مِنَ الْعُيُونِ',
      transliteration: 'Wa ja\'alnaa feehaa jannaatim min nakheelinw wa a\'naabinw wa fajjarnaa feeha minal \'uyoon',
      translation: '34) Dan Kami jadikan padanya di bumi itu kebun-kebun kurma dan anggur dan Kami pancarkan padanya beberapa mata air,',
    ),
    YasinVerse(
      number: 35,
      arabic: 'لِيَأْكُلُوا مِن ثَمَرِهِ وَمَا عَمِلَتْهُ أَيْدِيهِمْ ۖ أَفَلَا يَشْكُرُونَ',
      transliteration: 'Liyaakuloo min samarihee wa maa \'amilat-hu aideehim; afalaa yashkuroon',
      translation: '35) agar mereka dapat makan dari buahnya, dan dari hasil usaha tangan mereka. Maka mengapa mereka tidak bersyukur?',
    ),
    YasinVerse(
      number: 36,
      arabic: 'سُبْحَانَ الَّذِي خَلَقَ الْأَزْوَاجَ كُلَّهَا مِمَّا تُنبِتُ الْأَرْضُ وَمِنْ أَنفُسِهِمْ وَمِمَّا لَا يَعْلَمُونَ',
      transliteration: 'Subhaanal lazee khalaqal azwaaja kullahaa mimmaa tumbitul ardu wa min anfusihim wa mimmaa laa ya\'lamoon',
      translation: '36) Mahasuci (Allah) yang telah menciptakan semuanya berpasang-pasangan, baik dari apa yang ditumbuhkan oleh bumi dan dari diri mereka sendiri, maupun dari apa yang tidak mereka ketahui.',
    ),
    YasinVerse(
      number: 37,
      arabic: 'وَآيَةٌ لَّهُمُ اللَّيْلُ نَسْلَخُ مِنْهُ النَّهَارَ فَإِذَا هُم مُّظْلِمُونَ',
      transliteration: 'Wa Aayatul lahumul lailu naslakhu minhun nahaara fa-izaa hum muzlimoon',
      translation: '37) Dan suatu tanda (kebesaran Allah) bagi mereka adalah malam; Kami tanggalkan siang dari (malam) itu, maka seketika itu mereka (berada dalam) kegelapan,',
    ),
    YasinVerse(
      number: 38,
      arabic: 'وَالشَّمْسُ تَجْرِي لِمُسْتَقَرٍّ لَّهَا ۚ ذَٰلِكَ تَقْدِيرُ الْعَزِيزِ الْعَلِيمِ',
      transliteration: 'Wash-shamsu tajree limustaqarril lahaa; zaalika taqdeerul \'Azeezil Aleem',
      translation: '38) dan matahari berjalan di tempat peredarannya. Demikianlah ketetapan (Allah) Yang Mahaperkasa, Maha Mengetahui.',
    ),
    YasinVerse(
      number: 39,
      arabic: 'وَالْقَمَرَ قَدَّرْنَاهُ مَنَازِلَ حَتَّىٰ عَادَ كَالْعُرْجُونِ الْقَدِيمِ',
      transliteration: 'Walqamara qaddarnaahu manaazila hattaa \'aada kal\'ur joonil qadeem',
      translation: '39) Dan telah Kami tetapkan tempat peredaran bagi bulan, sehingga (setelah ia sampai ke tempat peredaran yang terakhir) kembalilah ia seperti bentuk tandan yang tua.',
    ),
    YasinVerse(
      number: 40,
      arabic: 'لَا الشَّمْسُ يَنبَغِي لَهَا أَن تُدْرِكَ الْقَمَرَ وَلَا اللَّيْلُ سَابِقُ النَّهَارِ ۚ وَكُلٌّ فِي فَلَكٍ يَسْبَحُونَ',
      transliteration: 'Lash shamsu yambaghee lahaaa an tudrikal qamara wa lal lailu saabiqun nahaar; wa kullun fee falaki yasbahoon',
      translation: '40) Tidaklah mungkin bagi matahari mengejar bulan dan malam pun tidak dapat mendahului siang. Masing-masing beredar pada garis edarnya.',
    ),
    YasinVerse(
      number: 41,
      arabic: 'وَآيَةٌ لَّهُمْ أَنَّا حَمَلْنَا ذُرِّيَّتَهُمْ فِي الْفُلْكِ الْمَشْحُونِ',
      transliteration: 'Wa Aayatul lahum annaa hamalnaa zurriyatahum fil fulkil mashhoon',
      translation: '41) Dan suatu tanda (kebesaran Allah) bagi mereka adalah bahwa Kami angkut keturunan mereka dalam kapal yang penuh muatan,',
    ),
    YasinVerse(
      number: 42,
      arabic: 'وَخَلَقْنَا لَهُم مِّن مِّثْلِهِ مَا يَرْكَبُونَ',
      transliteration: 'Wa khalaqnaa lahum mim-mislihee maa yarkaboon',
      translation: '42) dan Kami ciptakan (juga) untuk mereka (angkutan lain) seperti apa yang mereka kendarai.',
    ),
    YasinVerse(
      number: 43,
      arabic: 'وَإِن نَّشَأْ نُغْرِقْهُمْ فَلَا صَرِيخَ لَهُمْ وَلَا هُمْ يُنقَذُونَ',
      transliteration: 'Wa in nashaa nughriqhum falaa sareekha lahum wa laa hum yunqazoon',
      translation: '43) Dan jika Kami menghendaki, Kami tenggelamkan mereka. Maka tidak ada penolong bagi mereka dan tidak (pula) mereka diselamatkan,',
    ),
    YasinVerse(
      number: 44,
      arabic: 'إِلَّا رَحْمَةً مِّنَّا وَمَتَاعًا إِلَىٰ حِينٍ',
      transliteration: 'Illaa rahmatam minnaa wa mataa\'an ilaa heen',
      translation: '44) melainkan (Kami selamatkan mereka) karena rahmat yang besar dari Kami dan untuk memberikan kesenangan hidup sampai waktu tertentu.',
    ),
    YasinVerse(
      number: 45,
      arabic: 'وَإِذَا قِيلَ لَهُمُ اتَّقُوا مَا بَيْنَ أَيْدِيكُمْ وَمَا خَلْفَكُمْ لَعَلَّكُمْ تُرْحَمُونَ',
      transliteration: 'Wa izaa qeela lahumuttaqoo maa baina aideekum wa maa khalfakum la\'allakum turhamoon',
      translation: '45) Dan apabila dikatakan kepada mereka, “Takutlah kamu akan siksa yang di hadapanmu (di dunia) dan azab yang akan datang (akhirat) agar kamu mendapat rahmat.”',
    ),
    YasinVerse(
      number: 46,
      arabic: 'وَمَا تَأْتِيهِم مِّنْ آيَةٍ مِّنْ آيَاتِ رَبِّهِمْ إِلَّا كَانُوا عَنْهَا مُعْرِضِينَ',
      transliteration: 'Wa maa taateehim min aayatim min ayataati Rabbihim illaa kaanoo \'anhaa mu\'rideen',
      translation: '46) Dan setiap kali suatu tanda dari tanda-tanda (kebesaran) Tuhan datang kepada mereka, mereka selalu berpaling darinya.',
    ),
    YasinVerse(
      number: 47,
      arabic: 'وَإِذَا قِيلَ لَهُمْ أَنفِقُوا مِمَّا رَزَقَكُمُ اللَّهُ قَالَ الَّذِينَ كَفَرُوا لِلَّذِينَ آمَنُوا أَنُطْعِمُ مَن لَّوْ يَشَاءُ اللَّهُ أَطْعَمَهُ إِنْ أَنتُمْ إِلَّا فِي ضَلَالٍ مُّبِينٍ',
      transliteration: 'Wa izaa qeela lahum anfiqoo mimmaa razaqakumul laahu qaalal lazeena kafaroo lillazeena aamanooo anut\'imu mal-law yashaaa\'ul laahu at\'amahooo in antum illaa fee dalaalim mubeen',
      translation: '47) Dan apabila dikatakan kepada mereka, “Infakkanlah sebagian rezeki yang diberikan Allah kepadamu,” orang-orang yang kafir itu berkata kepada orang-orang yang beriman, “Apakah pantas kami memberi makan kepada orang-orang yang jika Allah menghendaki Dia akan memberinya makan? Kamu benar-benar dalam kesesatan yang nyata.”',
    ),
    YasinVerse(
      number: 48,
      arabic: 'وَيَقُولُونَ مَتَىٰ هَٰذَا الْوَعْدُ إِن كُنتُمْ صَادِقِينَ',
      transliteration: 'Wa yaqooloona mataa haazal wa\'du in kuntum saadiqeen',
      translation: '48) Dan mereka (orang-orang kafir) berkata, “Kapan janji (hari berbangkit) itu (terjadi) jika kamu orang yang benar?”',
    ),
    YasinVerse(
      number: 49,
      arabic: 'مَا يَنظُرُونَ إِلَّا صَيْحَةً وَاحِدَةً تَأْخُذُهُمْ وَهُمْ يَخِصِّمُونَ',
      transliteration: 'Maa yanzuroona illaa saihatanw waahidatan taa khuzuhum wa hum yakhissimoon',
      translation: '49) Mereka hanya menunggu satu teriakan, yang akan membinasakan mereka ketika mereka sedang bertengkar.',
    ),
    YasinVerse(
      number: 50,
      arabic: 'فَلَا يَسْتَطِيعُونَ تَوْصِيَةً وَلَا إِلَىٰ أَهْلِمْ يَرْجِعُونَ',
      transliteration: 'Falaa yastatee\'oona taw siyatanw-wa laaa ilaaa ahlihim yarji\'oon',
      translation: '50) Sehingga mereka tidak mampu membuat suatu wasiat dan mereka (juga) tidak dapat kembali kepada keluarganya.',
    ),
    YasinVerse(
      number: 51,
      arabic: 'وَنُفِخَ فِي الصُّورِ فَإِذَا هُم مِّنَ الْأَجْدَاثِ إِلَىٰ رَبِّهِمْ يَنسِلُونَ',
      transliteration: 'Wa nufikha fis-soori faizaa hum minal ajdaasi ilaa Rabbihim yansiloon',
      translation: '51) Lalu ditiuplah sangkakala, maka seketika itu mereka keluar dari kuburnya (dalam keadaan hidup), menuju kepada Tuhannya.',
    ),
    YasinVerse(
      number: 52,
      arabic: 'قَالُوا يَا وَيْلَنَا مَن بَعَثَنَا مِن مَّرْقَدِنَا ۜ ۗ هَٰذَا مَا وَعَدَ الرَّحْمَٰنُ وَصَدَقَ الْمُرْسَلُونَ',
      transliteration: 'Qaaloo yaa wailanaa mam ba\'asanaa mim marqadinaa; haaza maa wa\'adar Rahmanu wa sadaqal mursaloon',
      translation: '52) Mereka berkata, “Celakalah kami! Siapakah yang bangkitkan kami dari tempat tidur kami (kubur)?” Inilah yang dijanjikan (Allah) Yang Maha Pengasih dan benarlah rasul-rasul(-Nya).',
    ),
    YasinVerse(
      number: 53,
      arabic: 'إِن كَانَتْ إِلَّا صَيْحَةً وَاحِدَةً فَإِذَا هُمْ جَمِيعٌ لَّدَيْنَا مُحْضَرُونَ',
      transliteration: 'In kaanat illaa saihatanw waahidatan fa-izaa hum jamee\'ul ladainaa muhdaroon',
      translation: '53) Teriakan itu hanya sekali saja, maka seketika itu mereka semua dihadapkan kepada Kami (untuk dihisab).',
    ),
    YasinVerse(
      number: 54,
      arabic: 'فَالْيَوْمَ لَا تُظْلَمُ نَفْسٌ شَيْئًا وَلَا تُجْزَوْنَ إِلَّا مَا كُنتُمْ تَعْمَلُونَ',
      transliteration: 'Fal-Yawma laa tuzlamu nafsun shai\'anw-wa laa tujzawna illaa maa kuntum ta\'maloon',
      translation: '54) Maka pada hari itu seseorang tidak akan dirugikan sedikit pun dan kamu tidak akan diberi balasan, kecuali sesuai dengan apa yang telah kamu kerjakan.',
    ),
    YasinVerse(
      number: 55,
      arabic: 'إِنَّ أَصْحَابَ الْجَنَّةِ الْيَوْمَ فِي شُغُلٍ فَاكِهُونَ',
      transliteration: 'Inna Ashaabal jannatil Yawma fee shughulin faakihoon',
      translation: '55) Sesungguhnya penghuni surga pada hari itu bersenang-senang dalam kesibukan (mereka).',
    ),
    YasinVerse(
      number: 56,
      arabic: 'هُمْ وَأَزْوَاجُهُمْ فِي ظِلَالٍ عَلَى الْأَرَائِكِ مُتَّكِئُونَ',
      transliteration: 'Hum wa azwaajuhum fee zilaalin \'alal araaa\'iki muttaki\'oon',
      translation: '56) Mereka dan pasangan-pasangannya berada dalam tempat yang teduh, bersandar di atas dipan-dipan.',
    ),
    YasinVerse(
      number: 57,
      arabic: 'لَهُمْ فِيهَا فَاكِهَةٌ وَلَهُم مَّا يَدَّعُونَ',
      transliteration: 'Lahum feehaa faakiha tunw-wa lahum maa yadda\'oon',
      translation: '57) Di surga itu mereka memperoleh buah-buahan dan memperoleh apa saja yang mereka inginkan.',
    ),
    YasinVerse(
      number: 58,
      arabic: 'سَلَامٌ قَوْلًا مِّن رَّبٍّ رَّحِيمٍ',
      transliteration: 'Salaamun qawlam mir Rabbir Raheem',
      translation: '58) (Kepada mereka dikatakan), “Salam,” sebagai ucapan selamat dari Tuhan Yang Maha Penyayang.',
    ),
    YasinVerse(
      number: 59,
      arabic: 'وَامْتَازُوا الْيَوْمَ أَيُّهَا الْمُجْرِمُونَ',
      transliteration: 'Wamtaazul Yawma ayyuhal mujrimoon',
      translation: '59) Dan (dikatakan kepada orang-orang kafir), “Berpisahlah kamu (dari orang-orang mukmin) pada hari ini, wahai orang-orang yang berdosa!',
    ),
    YasinVerse(
      number: 60,
      arabic: '۞ أَلَمْ أَعْهَدْ إِلَيْكُمْ يَا بَنِي آدَمَ أَن لَّا تَعْبُدُوا الشَّيْطَانَ ۖ إِنَّهُ لَكُمْ عَدُوٌّ مُّبِينٌ',
      transliteration: 'Alam a\'had ilaikum yaa Baneee Aadama al-laa ta\'budush Shaitaana innahoo lakum \'aduwwum mubeen',
      translation: '60) Bukankah Aku telah memerintahkan kepadamu wahai anak cucu Adam agar kamu tidak menyembah setan? Sungguh, setan itu musuh yang nyata bagi kamu,',
    ),
    YasinVerse(
      number: 61,
      arabic: 'وَأَنِ اعْبُدُونِي ۚ هَٰذَا صِرَاطٌ مُّسْتَقِيمٌ',
      transliteration: 'Wa ani\'budoonee; haazaa Siraatum Mustaqeem',
      translation: '61) dan hendaklah kamu menyembah-Ku. Inilah jalan yang lurus.”',
    ),
    YasinVerse(
      number: 62,
      arabic: 'وَلَقَدْ أَضَلَّ مِنكُمْ جِبِلًّا كَثِيرًا ۖ أَفَلَمْ تَكُونُوا تَعْقِلُونَ',
      transliteration: 'Wa laqad adalla minkum jibillan kaseeraa; afalam takoonoo ta\'qiloon',
      translation: '62) Dan sungguh, ia (setan itu) telah menyesatkan sebagian besar di antara kamu. Maka apakah kamu tidak mengerti?',
    ),
    YasinVerse(
      number: 63,
      arabic: 'هَٰذِهِ جَهَنَّمُ الَّتِي كُنتُمْ تُوعَدُونَ',
      transliteration: 'Haazihee Jahannamul latee kuntum too\'adoon',
      translation: '63) Inilah (neraka) Jahanam yang dahulu telah diperingatkan kepadamu.',
    ),
    YasinVerse(
      number: 64,
      arabic: 'اصْلَوْهَا الْيَوْمَ بِمَا كُنتُمْ تَكْفُرُونَ',
      transliteration: 'Islawhal Yawma bimaa kuntum takfuroon',
      translation: '64) Masuklah ke dalamnya pada hari ini karena dahulu kamu mengingkarinya.',
    ),
    YasinVerse(
      number: 65,
      arabic: 'الْيَوْمَ نَخْتِمُ عَلَىٰ أَفْوَاهِهِمْ وَتُكَلِّمُنَا أَيْدِيهِمْ وَتَشْهَدُ أَرْجُلُهُم بِمَا كَانُوا يَكْسِبُونَ',
      transliteration: 'Al-Yawma nakhtimu \'alaaa afwaahihim wa tukallimunaaa aideehim wa tashhadu arjuluhum bimaa kaanoo yaksiboon',
      translation: '65) Pada hari ini Kami tutup mulut mereka; tangan mereka akan berkata kepada Kami dan kaki mereka akan memberi kesaksian terhadap apa yang dahulu mereka kerjakan.',
    ),
    YasinVerse(
      number: 66,
      arabic: 'وَلَوْ نَشَاءُ لَطَمَسْنَا عَلَىٰ أَعْيُنِهِمْ فَاسْتَبَقُوا الصِّرَاطَ فَأَنَّىٰ يُبْصِرُونَ',
      transliteration: 'Wa law nashaaa\'u lata masna \'alaaa aiyunihim fasta baqus-siraata fa-annaa yubsiroon',
      translation: '66) Dan jika Kami menghendaki, pastilah Kami hapuskan penglihatan mata mereka; sehingga mereka berlomba-lomba (mencari) jalan. Maka bagaimana mungkin mereka dapat melihat?',
    ),
    YasinVerse(
      number: 67,
      arabic: 'وَلَوْ نَشَاءُ لَمَسَخْنَاهُمْ عَلَىٰ مَكَانَتِهِمْ فَمَا اسْتَطَاعُوا مُضِيًّا وَلَا يَرْجِعُونَ',
      transliteration: 'Wa law nashaaa\'u lamasakhnaahum \'alaa makaanatihim famas-tataa\'oo mudiyyanw-wa laa yarji\'oon',
      translation: '67) Dan jika Kami menghendaki, pastilah Kami ubah bentuk mereka di tempat mereka berada; sehingga mereka tidak sanggup berjalan lagi dan juga tidak sanggup kembali.',
    ),
    YasinVerse(
      number: 68,
      arabic: 'وَمَن نُّعَمِّرْهُ نُنَكِّسْهُ فِي الْخَلْقِ ۖ أَفَلَا يَعْقِلُونَ',
      transliteration: 'Wa man nu \'ammirhu nunakkishu fil-khalq; afalaa ya\'qiloon',
      translation: '68) Dan barangsiapa Kami panjangkan umurnya niscaya Kami kembalikan dia kepada awal kejadian(nya). Maka mengapa mereka tidak mengerti?',
    ),
    YasinVerse(
      number: 69,
      arabic: 'وَمَا عَلَّمْنَاهُ الشِّعْرَ وَمَا يَنبَغِي لَهُ ۚ إِنْ هُوَ إِلَّا ذِكْرٌ وَقُرْآنٌ مُّبِينٌ',
      transliteration: 'Wa maa \'allamnaahush shi\'ra wa maa yambaghee lah; in huwa illaa zikrunw-wa Qur-aanum mubeen',
      translation: '69) Dan Kami tidak mengajarkan syair kepadanya (Muhammad) dan bersyair itu tidaklah pantas baginya. Al-Qur\'an itu tidak lain hanyalah pelajaran dan Kitab yang jelas,',
    ),
    YasinVerse(
      number: 70,
      arabic: 'لِّيُنذِرَ مَن كَانَ حَيًّا وَيَحِقَّ الْقَوْلُ عَلَى الْكَافِرِينَ',
      transliteration: 'Liyunzira man kaana haiyanw-wa yahiqqal qawlu \'alal-kaafireen',
      translation: '70) agar dia (Muhammad) memberi peringatan kepada orang-orang yang hidup (hatinya) dan agar pasti ketetapan (azab) terhadap orang-orang kafir.',
    ),
    YasinVerse(
      number: 71,
      arabic: 'أَوَلَمْ يَرَوْا أَنَّا خَلَقْنَا لَهُم مِّمَّا عَمِلَتْ أَيْدِينَا أَنْعَامًا فَهُمْ لَهَا مَالِكُونَ',
      transliteration: 'Awalam yaraw annaa khalaqnaa lahum mimmaa \'amilat aideenaaa an\'aaman fahum lahaa maalikoon',
      translation: '71) Dan tidakkah mereka melihat bahwa Kami telah menciptakan hewan ternak untuk mereka, yaitu sebagian dari apa yang telah Kami ciptakan dengan kekuasaan Kami, lalu mereka menguasainya?',
    ),
    YasinVerse(
      number: 72,
      arabic: 'وَذَلَّلْنَاهَا لَهُمْ فَمِنْهَا رَكُوبُهُمْ وَمِنْهَا يَأْكُلُونَ',
      transliteration: 'Wa zallalnaahaa lahum faminhaa rakoobuhum wa minhaa yaakuloon',
      translation: '72) Dan Kami menundukkannya (hewan-hewan itu) untuk mereka; lalu sebagiannya untuk menjadi tunggangan mereka dan sebagian untuk mereka makan.',
    ),
    YasinVerse(
      number: 73,
      arabic: 'وَلَهُمْ فِيهَا مَنَافِعُ وَمَشَارِبُ ۖ أَفَلَا يَشْكُرُونَ',
      transliteration: 'Wa lahum feehaa manaa fi\'u wa mashaarib; afalaa yashkuroon',
      translation: '73) Dan mereka memperoleh berbagai manfaat dan minuman darinya. Maka mengapa mereka tidak bersyukur?',
    ),
    YasinVerse(
      number: 74,
      arabic: 'وَاتَّخَذُوا مِن دُونِ اللَّهِ آلِهَةً لَّعَلَّهُمْ يُنصَرُونَ',
      transliteration: 'Wattakhazoo min doonil laahi aalihatal la\'allahum yunsaroon',
      translation: '74) Dan mereka mengambil sesembahan selain Allah agar mereka mendapat pertolongan.',
    ),
    YasinVerse(
      number: 75,
      arabic: 'لَا يَسْتَطِيعُونَ نَصْرَهُمْ وَهُمْ لَهُمْ جُندٌ مُّحْضَرُونَ',
      transliteration: 'Laa yastatee\'oona nasrahum wa hum lahum jundum muhdaroon',
      translation: '75) Mereka (sesembahan) itu tidak dapat menolong mereka; padahal mereka itu menjadi tentara yang disiapkan untuk menjaga (sesembahan) itu.',
    ),
    YasinVerse(
      number: 76,
      arabic: 'فَلَا يَحْزُنكَ قَوْلُهُمْ ۘ إِنَّا نَعْلَمُ مَا يُسِرُّونَ وَمَا يُعْلِنُونَ',
      transliteration: 'Falaa yahzunka qawluhum; innaa na\'lamu maa yusirroona wa maa yu\'linoon',
      translation: '76) Maka jangan sampai ucapan mereka membuat engkau (Muhammad) bersedih hati. Sungguh, Kami mengetahui apa yang mereka rahasiakan dan apa yang mereka nyatakan.',
    ),
    YasinVerse(
      number: 77,
      arabic: 'أَوَلَمْ يَرَ الْإِنسَانُ أَنَّا خَلَقْنَا هُ مِن نُّطْفَةٍ فَإِذَا هُوَ خَصِيمٌ مُّبِينٌ',
      transliteration: 'Awalam yaral insaanu annaa khalaqnaahu min nutfatin fa-izaa huwa khaseemum mubeen',
      translation: '77) Dan tidakkah manusia memperhatikan bahwa Kami menciptakannya dari setetes mani, ternyata dia menjadi musuh yang nyata!',
    ),
    YasinVerse(
      number: 78,
      arabic: 'وَضَرَبَ لَنَا مَثَلًا وَنَسِيَ خَلْقَهُ ۖ قَالَ مَن يُحْيِي الْعِظَامَ وَهِيَ رَمِيمٌ',
      transliteration: 'Wa daraba lanaa maslanw-wa nasiya khalqahoo qaala mai-yuhyil\'izaama wa hiya rameem',
      translation: '78) Dan dia membuat perumpamaan bagi Kami dan melupakan asal kejadiannya; dia berkata, “Siapakah yang dapat menghidupkan tulang-belulang, yang telah hancur luluh?”',
    ),
    YasinVerse(
      number: 79,
      arabic: 'قُلْ يُحْيِيهَا الَّذِي أَنشَأَهَا أَوَّلَ مَرَّةٍ ۖ وَهُوَ بِكُلِّ خَلْقٍ عَلِيمٌ',
      transliteration: 'Qul yuh yeehal lazeee ansha ahaaa awwala marrah; wa Huwa bikulli khalqin \'Aleem',
      translation: '79) Katakanlah (Muhammad), “Yang akan menghidupkannya ialah (Allah) yang menciptakannya pertama kali. Dan Dia Maha Mengetahui tentang segala makhluk,',
    ),
    YasinVerse(
      number: 80,
      arabic: 'الَّذِي جَعَلَ لَكُم مِّنَ الشَّجَرِ الْأَخْضَرِ نَارًا فَإِذَا أَنتُم مِّنْهُ تُوقِدُونَ',
      transliteration: 'Allazee ja\'ala lakum minash shajaril akhdari naaran fa-izaaa antum minhu tooqidoon',
      translation: '80) yaitu (Allah) yang menjadikan api untukmu dari kayu yang hijau, maka seketika itu kamu nyalakan (api) dari kayu itu.”',
    ),
    YasinVerse(
      number: 81,
      arabic: 'أَوَلَيْسَ الَّذِي خَلَقَ السَّمَاوَاتِ وَالْأَرْضَ بِقَادِرٍ عَلَىٰ أَن يَخْلُقَ مِثْلَهُم ۚ بَلَىٰ وَهُوَ الْخَلَّاقُ الْعَلِيمُ',
      transliteration: 'Awa laisal lazee khalaqas samaawaati wal arda biqaadirin \'alaaa ai-yakhluqa mislahum; balaa wa Huwal Khallaaqul \'Aleem',
      translation: '81) Dan bukankah (Allah) yang menciptakan langit dan bumi, mampu menciptakan kembali yang serupa itu (jasad mereka yang sudah hancur itu)? Benar, dan Dia Maha Pencipta, Maha Mengetahui.',
    ),
    YasinVerse(
      number: 82,
      arabic: 'إِنَّمَا أَمْرُهُ إِذَا أَرَادَ شَيْئًا أَن يَقُولَ لَهُ كُن فَيَكُونُ',
      transliteration: 'Innamaa amruhooo izaaa araada shai\'an ai-yaqoola lahoo kun fa-yakoon',
      translation: '82) Sesungguhnya urusan-Nya apabila Dia menghendaki sesuatu Dia hanya berkata kepadanya, “Jadilah!” Maka jadilah sesuatu itu.',
    ),
    YasinVerse(
      number: 83,
      arabic: 'فَسُبْحَانَ الَّذِي بِيَدِهِ مَلَكُوتُ كُلِّ شَيْءٍ وَإِلَيْهِ تُرْجَعُونَ',
      transliteration: 'Fa Subhaanal lazee biyadihee malakootu kulli shai-inw-wa ilaihi turja\'oon',
      translation: '83) Maka Mahasuci (Allah) yang di tangan-Nya kekuasaan atas segala sesuatu dan kepada-Nya kamu dikembalikan.',
    ),
  ];
}
